### ISSUE TITLE
Example JSON files 

### ISSUE THREAD

**Issue by pbertsch** [jelic98/dynamico#1]
@jelic98 
Could you provide *JSON files* as a catalog of Demo files. It would be interesting to see the structure of those files. Maybe you still have the files you used for testing.

Do you accept PR's ?

**Comment by jelic98** [comment]
There is a manual that contains all JSON examples. You can take a look at it here: https://github.com/jelic98/dynamico/blob/master/MANUAL.md

Feel free to add some features and when you're finished create a PR.

**Comment by pbertsch** [comment]
That's what I was looking for. Thx @jelic98
