### ISSUE TITLE
Enhancement - New attributes left, right, top, bottom margin

### ISSUE THREAD

**Issue by pbertsch** [jelic98/dynamico#5]
@jelic98 
making the left,right,top,bottom-Margin attributes easier to handle by allowing  to add a single attr. if necessary.

- leftMargin
- rightMargin
- topMargin
- bottomMargin

PR #4

**Comment by jelic98** [comment]
These attributes already exist. I've decided to use start/end instead of left/right. Please, take a look at line 236 in MANUAL. I will close this issue now.
